### ISSUE TITLE
Use poetry

### ISSUE THREAD

**Issue by trag1c** [trag1c/mcoding-all-dunders#31]

**Comment by Endercheif** [comment]
What’s the point of using Poetry for this? It is unnecessary. We only have development requirements for which their versioning doesn’t need to be locked as much as this. `requirements.txt` is perfectly fine. Also for non Poetry contributors this takes away from the simplicity.

smh

**Comment by trag1c** [comment]
## Pros
- `poetry install` is simpler than `pip install -r requirements.txt`
- dependencies aren't installed globally
- black is pretty much guaranteed to work correctly with a script
- checking code would be 1 less command to run (`poetry run ci`?)
- same for fixing it (`poetry run fix`?)

## Cons
- non-Poetry users have to install it (which is also just one command iirc)
- `poetry install` might take more time than `pip install -r requirements.txt`

I'm **not yet** convinced using Poetry here "is unnecessary and overcomplicates stuff" 🤷‍♂️

(On a side note I didn't mean to lock the versions that much, I just realized this lol)

**Comment by CircuitSacul** [comment]
I think poetry simplifies things for people who already use it, and makes things easier for newer python users. For people who just don't like poetry, you still don't have to use poetry - there's only two requirements, black and ruff, which can be installed easily.

I don't think it hurts to add poetry.

**Comment by Lunarmagpie** [comment]
> dependencies aren't installed globally

Black and mypy don't usually have enough changes for this to matter, but that's whatever. Mainly I expect anyone who can contribute dunders at this point to know what a venv is.

 > black is pretty much guaranteed to work correctly with a script

Just lock the version in requirements.txt so each new install is guaranteed to work.

> checking code would be 1 less command to run (poetry run ci?)
same for fixing it (poetry run fix?)

Poetry doesn't do this. I think you want nox.

I don't see the point of this addition. It doesn't make anything simpler and it will slow down the GitHub actions. In my other projects adding poetry will make ci go from under 20 seconds to over a minute.
Another issue with poetry is that this project is most definitely not a package, it doesn't make sense to add a build tool for packages. Dependency and venv management can be done in a few commands already.

**Comment by trag1c** [comment]
> Black and mypy don't usually have enough changes for this to matter, but that's whatever. Mainly I expect anyone who can contribute dunders at this point to know what a venv is.

Fair enough :+1:

> Just lock the version in requirements.txt so each new install is guaranteed to work.

Well it is locked but it still didn't work sometimes for some people (incl. me).

> Poetry doesn't do this. I think you want nox.

https://python-poetry.org/docs/pyproject/#scripts
But yeah now I think it's a pretty bad way to do this. Do you think nox is something we'd potentially want instead?

> it will slow down the GitHub actions. In my other projects adding poetry will make ci go from under 20 seconds to over a minute.

That's a great point, I totally didn't consider this.
